Byook/ByookWebApp/Controllers/MemberController.cs
using Byook.Utility.Interface;
using Byook.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

namespace Byook.Controllers
{
    public sealed class MemberController : Controller
    {
        private readonly ByookDbContext context;
        private readonly IConfiguration configuration;
        private readonly IJwtTokenGenerator tokenGenerator;

        public MemberController(ByookDbContext context, IConfiguration configuration, IJwtTokenGenerator tokenGenerator)
        {
            this.context = context;
            this.configuration = configuration;
            this.tokenGenerator = tokenGenerator;
        }

        [HttpGet]
        [Route("/api/member/sellers")]
        public async Task<IActionResult> IsSellerRegistered([FromQuery] string businessNumber)
        {
            IActionResult result = Unauthorized();

            try
            {
                var user = await context.Seller!
                    .AsNoTracking()
                    .FirstOrDefaultAsync(d => d.Id.Equals(businessNumber));

                return Ok(user is not null);
            }
            catch(Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpGet]
        [Route("/api/member/consumers")]
        public async Task<IActionResult> IsConsumerRegistered([FromQuery] string businessNumber)
        {
            try
            {
                var user = await context.Consumer!
                .AsNoTracking()
                .FirstOrDefaultAsync(d => d.Id.Equals(businessNumber));

                return Ok(user is null);
            }
            catch(Exception)
            {
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
        }

        public IActionResult SellerLogin()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SellerLogin(SellerLoginViewModel user)
        {
            if(!ModelState.IsValid)
            {
                return View(user);
            }

            var hash = GeneratorHash(user.Password);
            var findUser = await context.Seller!.FirstOrDefaultAsync(u => u.Id.Equals(user.SellerId) && u.Password.Equals(hash));

            if(findUser is null)
            {
                return View(nameof(SellerLogin), user);
            }

            var accessTokenResult = tokenGenerator.GenerateAccessTokenWithClaimsPrincipal(user.SellerId, GeneratorClaims(user.SellerId, nameof(Seller)));

            await HttpContext.SignInAsync(accessTokenResult.ClaimsPrincipal!, accessTokenResult.AuthProperties!);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult ConsumerLogin()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConsumerLogin(ConsumerLoginViewModel user)
        {
            if(!ModelState.IsValid)
            {
                var errorItem = ModelState.FirstOrDefault(d => d.Value!.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid).Key;
                TempData["Error"] = errorItem;

                return View(user);
            }

            var hash = GeneratorHash(user.Password);
            var findUser = await context.Consumer!.FirstOrDefaultAsync(u => u.Id.Equals(user.ConsumerId) && u.Password.Equals(hash));

            if(findUser is null)
            {
                return View(nameof(SellerLogin), user);
            }

            var accessTokenResult = tokenGenerator.GenerateAccessTokenWithClaimsPrincipal(user.ConsumerId, GeneratorClaims(user.ConsumerId, nameof(Consumer)));

            await HttpContext.SignInAsync(accessTokenResult.ClaimsPrincipal!, accessTokenResult.AuthProperties!);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult ConsumerRegister()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ConsumerRegister(Consumer model)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            using var sha512 = SHA512.Create();

            var passwordBytes = Encoding.Default.GetBytes(model.Password);
            var passwordHash = sha512.ComputeHash(passwordBytes);
            var hash = BitConverter.ToString(passwordHash).Replace("-", string.Empty);

            await context.Consumer!.AddAsync(model);
            await context.SaveChangesAsync();

            return RedirectToAction(nameof(ConsumerLogin));
        }

        public IActionResult SellerRegister()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SellerRegister(SellerRegisterViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            var hash = GeneratorHash(model.Seller!.Password);

            model.Seller!.Password = hash;
            model.Seller.Address = $"{model.Seller.Address} {model.OtherAddress}";

            try
            {
                await context.Seller!.AddAsync(model.Seller!);
                await context.SaveChangesAsync();
            }
            catch(Exception)
            {

            }

            return RedirectToAction(nameof(SellerLogin));
        }

        [Authorize(Policy = nameof(Seller))]
        public IActionResult SellerMyPage()
        {
            return View();
        }

        public IActionResult SelectRegister()
        {
            return View();
        }

        private string GeneratorHash(string password)
        {
            using var sha512 = SHA512.Create();

            var passwordBytes = Encoding.Default.GetBytes(password);
            var passwordHash = sha512.ComputeHash(passwordBytes);
            var hash = BitConverter.ToString(passwordHash).Replace("-", string.Empty);

            return hash;
        }

        private IList<Claim> GeneratorClaims(string id, string role)
        {
            var authClaims = new List<Claim>
        {
            new Claim(ClaimTypes.NameIdentifier, id),
            new Claim(ClaimTypes.Role, role),
        };

            return authClaims;
        }
    }
}

Byook/ByookWebApp/Controllers/ProductController.cs
using Byook.ViewModels;
using Newtonsoft.Json.Linq;
using NuGet.Packaging.Signing;
using System.Security.Claims;

namespace ByookWebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly ByookDbContext context;

        public ProductController(ByookDbContext context, IWebHostEnvironment hostEnvironment)
        {
            this.context = context;
            this.hostEnvironment = hostEnvironment;
        }

        [Authorize(Policy = nameof(Seller))]
        public async Task<IActionResult> Index()
        {
            var sellerId = User.Claims.FirstOrDefault(d => d.Type.Equals(ClaimTypes.NameIdentifier))!.Value;

            var products = context.Product!.Where(d => d.SellerId.Equals(sellerId));

            return View(await products.ToListAsync());
        }

        public IActionResult Details(int id)
        {
            return View();
        }

        [Authorize(Policy = nameof(Seller))]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product model, IFormFile? file)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            try
            {
                model.SellerId = GetSellerId();

                await UploadFileAndReturnUrl(model, file);

                await context.Product!.AddAsync(model);
                await context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private async Task UploadFileAndReturnUrl(Product model, IFormFile? file)
        {
            if(file is not null)
            {
                var rootPath = hostEnvironment.WebRootPath;
                var extension = Path.GetExtension(file.FileName);
                var uploadPath = Path.Combine(rootPath, @"saveImages\Products\");

                var saveImageName = Path.Combine(model.SellerId, model.CreateDate.ToString("yyyyMMddHHmmss"), extension).Replace("\\", string.Empty);

                using var fs = new FileStream(Path.Combine(uploadPath, saveImageName), FileMode.Create);

                await file.CopyToAsync(fs);

                model.ImageUrl = $@"/saveImages/Products/{saveImageName}";
            }
        }

        private void DeleteImage(string imageUrl)
        {
            if(System.IO.File.Exists($"{hostEnvironment.WebRootPath}{imageUrl}"))
            {
                System.IO.File.Delete($"{hostEnvironment.WebRootPath}{imageUrl}");
            }
        }

        // GET: ProductController/Edit/5
        [Authorize(Policy = nameof(Seller))]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await context.Product!.FirstOrDefaultAsync(d => d.Id == id);

            if(product is null)
            {
                return RedirectToAction(nameof(Index));
            }
            
            return View(product);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = nameof(Seller))]
        public async Task<IActionResult> Edit(Product model, IFormFile? file)
        {
            try
            {
                model.SellerId = GetSellerId();

                DeleteImage(model.ImageUrl);

                await UploadFileAndReturnUrl(model, file);

                context.Product!.Update(model);
                await context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete([FromBody] ProductDeleteViewModel model)
        {
            try
            {
                var product = await context.Product!.FirstOrDefaultAsync(d => d.SellerId == model.SellerId && d.Id == model.Productid);

                if(product is null || !product.ImageUrl.Equals(model.ImageUrl))
                {
                    return BadRequest("존재하지 않는 상품이거나 저장 되어있는 이미지의 경로가 다릅니다.");
                }

                DeleteFile(product.ImageUrl);

                context.Product!.Remove(product);

                await context.SaveChangesAsync();

                return Json("성공");
            }
            catch
            {
                return BadRequest("상품 삭제 중 에러 발생");
            }
        }

        private void DeleteFile(string filePath)
        {
            var fullPath = $"{hostEnvironment.WebRootPath}{filePath}";

            if(System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
        } 

        private string GetSellerId()
        {
            return User.Claims.FirstOrDefault(d => d.Type.Equals(ClaimTypes.NameIdentifier))!.Value;
        }
    }
}

Byook/ByookWebApp/Views/Member/ConsumerLogin.cshtml
@model ConsumerLoginViewModel

<div class="text-center mt-100">
    <h3 class=" mb-3">로그인</h3>
    <form method="post" asp-controller="Member" asp-action="ConsumerLogin">
        <div id="joinInfo" class="mt-5">
            <div>
                <input type="text" asp-for="ConsumerId" placeholder="아이디" />
            </div>
            <div>
                <input type="password" asp-for="Password" placeholder="비밀번호" />
            </div>
        </div>
        <div class="mb-3">
            <input class="btnRegister" type="submit" value="로그인" />
        </div>
    </form>
    <div>
        <a class="btnRegister" asp-controller="Member" asp-action="SellerLogin">
            <span>사업자 로그인</span>
        </a>
    </div>
</div>

Byook/ByookWebApp/Views/Member/ConsumerMyPage.cshtml
@model Consumer

<div class="text-center mt-100">
    <h3 class=" mb-3">로그인</h3>
    <form method="post" asp-controller="Member" asp-action="Login">
        <div id="joinInfo" class="mt-5">
            <div>
                <input type="text" asp-for="Id" placeholder="아이디" />
            </div>
            <div>
                <input type="password" asp-for="Password" placeholder="비밀번호" />
            </div>
        </div>
        <div class="mb-3">
            <input class="btnRegister" type="submit" value="로그인" />
        </div>
    </form>
    <div>
        <a class="btnRegister" asp-controller="Member" asp-action="SellerLogin">
            <span>사업자 로그인</span>
        </a>
    </div>
</div>

Byook/ByookWebApp/Views/Member/ConsumerRegister.cshtml
@model ConsumerRegisterViewModel

<div class="container mt-100">
    <h3 class="text-center mb-3">일반 회원가입</h3>
    <form method="post" asp-controller="Member" asp-action="ConsumerRegister">
        <table>
            <tr>
                <td>
                    <input type="text" id="businessNumber" asp-for="Consumer!.Id" placeholder="아이디" />
                    <button type="button" id="findBusinessNumber" class="button">중복 확인</button>
                    <input type="hidden" />
                </td>
            </tr>
            <tr>
                <td id="td_password">
                    <input type="password" id="password" asp-for="Consumer!.Password" placeholder="비밀번호" />
                    <p class="guide" style="display: none;">
                        <span class="case1">- 10자 이상 입력</span>
                        <span class="case2">- 영문/숫자/특수문자(공백 제외)만 허용하며, 2개 이상 조합</span>
                        <span class="case3">- 동일한 숫자 3개 이상 연속 사용 불가</span>
                    </p>
                </td>
            </tr>
            <tr>
                <td id="td_passwordConfirm">
                    <input type="password" id="passwordConfirm" placeholder="비밀번호 확인" />
                    <p class="guide" style="display: none;">
                        <span class="case1">- 동일한 비밀번호를 입력하세요 </span>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="address" asp-for="Consumer!.Address" disabled />
                    <button type="button" id="findAddress" class="button">주소 검색</button><br />
                    <input type="text" id="otherAddress" asp-for="OtherAddress" style="display: none;" class="mt-3" placeholder="나머지 주소를 입력하세요." />
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" asp-for="Consumer!.Name" placeholder="이름" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" asp-for="Consumer!.PhoneNumber" placeholder="휴대폰 번호" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <td>
                    <input class="btnRegister" type="submit" value="가입하기" />
                    <span></span>
                </td>
            </tr>
        </table>
    </form>
</div>

Byook/ByookWebApp/Views/Member/SelectRegister.cshtml
<div class="text-center mt-100">
    <h3>회원가입 종류</h3>
    <div class="mt-5">
        <a type="button" class="joinSelectButton me-2" asp-controller="Member" asp-action="ConsumerRegister">
            <h5 class="w-100">일반 회원가입</h5>
        </a>
        <a type="button" class="joinSelectButton" asp-controller="Member" asp-action="SellerRegister">
            <h5 class="w-100">사업자 회원가입</h5>
        </a>
    </div>
</div>

Byook/ByookWebApp/Views/Member/SellerLogin.cshtml
@model SellerLoginViewModel

<div class="text-center mt-100">
    <h3>사업자 로그인</h3>
    <form method="post" asp-controller="Member" asp-action="SellerLogin">
        <div id="joinInfo" class="mt-5">
            <div>
                <input type="text" asp-for="SellerId" placeholder="사업자 등록번호" />
            </div>
            <div>
                <input type="password" asp-for="Password" placeholder="비밀번호" />
            </div>
        </div>
        <div class="mb-3">
            <input class="btnRegister" type="submit" value="로그인" />
        </div>
    </form>
</div>

Byook/ByookWebApp/Views/Member/SellerMyPage.cshtml
@model Consumer

<div class="text-center mt-100">
    <h3 class=" pb-3 mb-0">마이페이지</h3>
    <div class="d-flex justify-content-evenly">
        <div>
            <a class="myPageBtn" asp-controller="" asp-action="">주문 조회</a>
        </div>
        <div>
            <a class="myPageBtn" asp-controller="Product" asp-action="Index">상품 조회</a>
        </div>
    </div>
</div>

Byook/ByookWebApp/Views/Member/SellerRegister.cshtml
@model SellerRegisterViewModel

<div class="container mt-100">
    <h3 class="text-center mb-3">사업자 회원가입</h3>
    <form method="post" asp-controller="Member" asp-action="SellerRegister">
        <table>
            <tr>
                <td>
                    <input type="text" id="businessNumber" asp-for="Seller!.Id" placeholder="사업자 등록번호" tabindex="1" />
                    <button type="button" id="findBusinessNumber" class="button">중복 확인</button>
                </td>
            </tr>
            <tr>
                <td id="td_password">
                    <input type="password" asp-for="Seller!.Password" id="password" placeholder="비밀번호" tabindex="2" />
                    <p class="guide" style="display: none;">
                        <span class="case1">- 10자 이상 입력</span>
                        <span class="case2">- 영문/숫자/특수문자(공백 제외)만 허용하며, 2개 이상 조합</span>
                        <span class="case3">- 동일한 숫자 3개 이상 연속 사용 불가</span>
                    </p>
                </td>
            </tr>
            <tr>
                <td id="td_passwordConfirm">
                    <input type="password" id="passwordConfirm" placeholder="비밀번호 확인" tabindex="3" />
                    <p class="guide" style="display: none;">
                        <span class="case1">- 동일한 비밀번호를 입력하세요 </span>
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="address" asp-for="Seller!.Address" readonly />
                    <button type="button" id="findAddress" class="button" tabindex="4">주소 검색</button><br />
                    <input type="text" id="otherAddress" style="display: none;" class="mt-3" asp-for="OtherAddress" placeholder="나머지 주소를 입력하세요." tabindex="5" />
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="name" asp-for="Seller!.Name" placeholder="이름" tabindex="6" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="tradeName" asp-for="Seller!.TradeName" placeholder="상호명" tabindex="7" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" id="phoneNumber" asp-for="Seller!.PhoneNumber" placeholder="휴대폰 번호" tabindex="8" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <td>
                    <input class="btnRegister" type="submit" value="가입하기" tabindex="9" />
                </td>
            </tr>
        </table>
    </form>
</div>


 <script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" async></script> 
<script src="~/js/SellerRegister.js" asp-append-version="true" async></script>